# Generated by Django 2.1.1 on 2018-09-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180917_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountManager',
        ),
    ]
